name: Yoepg to R2

on:
  schedule:
    - cron: '58 3,11,18 * * *'  # Запуск 3:58, 11:58, 18:58 GMT
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download File from Yo
        env:
          YO_URL: ${{ secrets.YO_URL }} # The secret containing the HTTP link yo-epg /xmltv/epg.xml.gz
        run: curl -o yoepg.xml.gz $YO_URL

      - name: Upload to R2
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          r2-bucket: epg
          source-dir: ./yoepg.xml.gz
          destination-dir: ./
