name: Upload File to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  download_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     - name: Download File from Yo
        env:
          YO_URL: ${{ secrets.YO_URL }} # The secret containing the HTTP link yo-epg /xmltv/epg.xml.gz
        run: curl -o yoepg.xml.gz $YO_URL

      - name: Upload to Cloudflare R2
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
          CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_BUCKET_NAME }}
        run: |
          aws configure set aws_access_key_id "$CLOUDFLARE_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$CLOUDFLARE_SECRET_ACCESS_KEY"
          aws configure set default.region eu-central-1
          aws s3 cp yoepg.xml.gz s3://$CLOUDFLARE_BUCKET_NAME/
